### ISSUE TITLE
Persistent XSS vulnerability

### ISSUE THREAD

**Issue by Snaacky** [dnutiu/benchmark-scoreboard#2]
Not sure how frequently you check your reddit PMs so I figured I would open an issue.

The log input on your /result POST request is vulnerable to XSS.

Two samples: (safe, you can check page source to see what I did)
http://www.denisnutiu.me/result/60
http://www.denisnutiu.me/result/61

**Comment by Snaacky** [comment]
Just to add, it looks like CPU and GPU are too.

**Comment by dnutiu** [comment]
Thanks! Apparently those fields are marked with the 'safe' filter in the view. I'm not exactly sure why I did that.

**Comment by dnutiu** [comment]
Fixed.
